name: setup
description: "Setup Node"
runs:
  using: "composite"
  steps:
    - name: "Setup Node"
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: "Cache Dependencies"
      id: cache
      uses: actions/cache@v3
      with: 
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    
    - name: "Install Dependencies"
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci